# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Check Apps For Errors

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  jhd-bot:

    runs-on: ubuntu-latest
    env:
      working-dir: ./JHDBot

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      working-directory: ${{env.working-dir}}
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      working-directory: ${{env.working-dir}}
    - name: Lint with pylint
      run: |
        pylint -E ${{env.working-dir}}
  
  verify-app:
    runs-on: ubuntu-latest
    env:
      working-dir: ./verify-web

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      working-directory: ${{env.working-dir}}
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      working-directory: ${{env.working-dir}}
    - name: Lint with pylint
      run: |
        pylint -E ${{env.working-dir}}
